#!/bin/env python

from glob import glob
import sys
sys.path.insert(0, '../20-exploring/')
from utilities import VenuesReader, GroupMemberReader
import  psycopg2, psycopg2.extras

data_dir = "../10-data/"

db_conn = psycopg2.connect("dbname='infovis_meetup'")
db_conn.autocommit = True
db_cursor = db_conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2:///infovis_meetup')

all_groups = [ path.replace("%s/events_updated/" % data_dir, "").replace(".json","") for path in glob("%s/events_updated/*.json" % data_dir) ]
print all_groups

for df in VenuesReader( all_groups , do_max = True):
  if not 'id_venue' in df.columns:
    print "skipping df with len=%d, columns %s" % ( len(df.index), df.columns.values) 
  else:
    df.to_sql('venues', engine, if_exists = 'append', index = False)

# manual fixes:  lat + lon cannot be null in python dataframes, have to find nulls again in postgres:    
db_cursor.execute("update venues set lat=null,lon=null where lat=0.0 and lon=0.0")
