group_4033532_cohorts.png: 
	echo "4033532" | ./plot_cohorts

group_4033532_cohorts.csv:
	echo "4033532" | ./extract_cohorts

group_4033532_retention.png:
	echo "4033532" | ./plot_retention

group_4033532_attendance.json: 
	echo "4033532" | ./scrape_attendance

