#!/bin/env python

from utilities import GroupsReader

onlyOnFirstFile = True
for df in GroupsReader( do_max = True, do_text = False ):
  print df.to_csv(encoding='utf-8', header = onlyOnFirstFile),
  onlyOnFirstFile = False
    

