#!/bin/env python

import matplotlib
import sys
import fileinput

from utilities import flatten_col, EventReader

# read list of json-files to work on from stdin
group_ids = [ f.strip() for f in fileinput.input() ]

# all_the_columns = set()
types_of_columns = {}

onlyOnFirstFile = True
for df in EventReader( group_ids ):
  d = df.dtypes.to_dict()
  types_of_columns.update( d )

s = repr( types_of_columns ).replace(", ", ",\n")

print s

    

