#!/bin/env python

from utilities import CategoryReader

onlyOnFirstFile = True
for df in CategoryReader( do_max = True, do_text = False ):
  print df.to_csv(encoding='utf-8', header = onlyOnFirstFile),
  onlyOnFirstFile = False
    

