#!/bin/env python

import matplotlib
import sys
import fileinput
import csv

from utilities import flatten_col, RsvpReader

# read list of json-files to work on from stdin
# group_ids = [ f.strip() for f in fileinput.input() ]

# all_the_columns = set()
# types_of_columns = {}

count = 0
onlyOnFirstFile = True
for df in RsvpReader( do_max = True ):
  count += 1
  print df.to_csv(encoding='utf-8', header = onlyOnFirstFile, quoting =  csv.QUOTE_NONNUMERIC),
  onlyOnFirstFile = False
    

