#!/bin/env python

import matplotlib
import sys
import fileinput

from utilities import flatten_col, EventReader

# read list of json-files to work on from stdin
group_ids = [ f.strip() for f in fileinput.input() ]

# all_the_columns = set()
# types_of_columns = {}

onlyOnFirstFile = True
for df in EventReader( group_ids, do_max = True ):
  print df.to_csv(encoding='utf-8', header = onlyOnFirstFile),
  onlyOnFirstFile = False
    

